/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Extracts documents and computes similarity against reference texts.
 *
 * Similarity is computed as a weighted blend of:
 * - content similarity (method-selected)
 * - metadata similarity (currently text metadata)
 *
 * # Parameters
 * - `documents`: Documents to extract and compare.
 * - `reference_texts`: Candidate reference texts.
 * - `similarity_threshold`: Minimum score (0-100) to include a match.
 *   Defaults to `30.0` when omitted.
 * - `similarity_method`: One of `jaccard`, `ngram`, `levenshtein`, `hybrid`.
 *   Defaults to `hybrid` when omitted or invalid.
 *
 * # Returns
 * Grouped documents with `similarity_matches` for references
 * whose score is greater than or equal to `similarity_threshold`.
 *
 * # Example
 * ```ts
 * import { computeDocumentSimilarity } from 'undms';
 *
 * const result = computeDocumentSimilarity(
 *   [document],
 *   ['reference text A', 'reference text B'],
 *   70,
 *   'hybrid',
 * );
 * ```
 */
export declare function computeDocumentSimilarity(documents: Array<Document>, referenceTexts: Array<string>, similarityThreshold?: number | undefined | null, similarityMethod?: string | undefined | null): Array<GroupedDocumentsWithSimilarity>

/**
 * Computes similarity matches for plain text input without file extraction.
 *
 * # Parameters
 * - `source_text`: Source text to compare.
 * - `reference_texts`: Candidate reference texts.
 * - `similarity_threshold`: Minimum score (0-100) to include a match.
 *   Defaults to `30.0` when omitted.
 * - `similarity_method`: One of `jaccard`, `ngram`, `levenshtein`, `hybrid`.
 *   Defaults to `hybrid` when omitted or invalid.
 *
 * # Returns
 * A list of `SimilarityMatch` values containing:
 * - `reference_index`: Index into `reference_texts`
 * - `similarity_percentage`: Final similarity score
 *
 * # Example
 * ```ts
 * import { computeTextSimilarity } from 'undms';
 *
 * const matches = computeTextSimilarity(
 *   'alpha beta gamma',
 *   ['alpha beta gamma', 'other'],
 *   80,
 *   'jaccard',
 * );
 * ```
 */
export declare function computeTextSimilarity(sourceText: string, referenceTexts: Array<string>, similarityThreshold?: number | undefined | null, similarityMethod?: string | undefined | null): Array<SimilarityMatch>

export interface Document {
  name: string
  size: number
  type: string
  lastModified: number
  webkitRelativePath: string
  buffer: Buffer
}

export interface DocumentMetadata {
  name: string
  size: number
  processingTime: number
  encoding: string
  content: string
  metadata?: MetadataPayload
  error?: string
}

export interface DocumentMetadataWithSimilarity {
  name: string
  size: number
  processingTime: number
  encoding: string
  content: string
  metadata?: MetadataPayload
  error?: string
  similarityMatches: Array<SimilarityMatch>
}

export interface DocxMetadata {
  paragraphCount: number
  tableCount: number
  imageCount: number
  hyperlinkCount: number
}

/**
 * Extracts content and metadata from input documents, grouped by MIME type.
 *
 * # Parameters
 * - `documents`: Input document list. Each document should include
 *   `name`, `type` (MIME), and `buffer` content.
 *
 * # Returns
 * Returns a list of groups keyed by MIME type.
 * Each document entry contains:
 * - `content`: Extracted plain text (empty when unsupported)
 * - `encoding`: Detected encoding (or `application/octet-stream`)
 * - `metadata`: Structured metadata payload when available
 * - `error`: Extraction error message when extraction fails
 * - `processing_time`: Extraction time in milliseconds
 *
 * # Example
 * ```ts
 * import { extract } from 'undms';
 *
 * const result = extract([
 *   {
 *     name: 'note.txt',
 *     size: 12,
 *     type: 'text/plain',
 *     lastModified: Date.now(),
 *     webkitRelativePath: '',
 *     buffer: Buffer.from('hello world!'),
 *   },
 * ]);
 * ```
 */
export declare function extract(documents: Array<Document>): Array<GroupedDocuments>

export interface GroupedDocuments {
  mimeType: string
  documents: Array<DocumentMetadata>
}

export interface GroupedDocumentsWithSimilarity {
  mimeType: string
  documents: Array<DocumentMetadataWithSimilarity>
}

export interface ImageLocation {
  latitude?: number
  longitude?: number
}

export interface ImageMetadata {
  width: number
  height: number
  format?: string
  cameraMake?: string
  cameraModel?: string
  datetimeOriginal?: string
  location: ImageLocation
}

export interface MetadataPayload {
  text?: TextMetadata
  docx?: DocxMetadata
  xlsx?: XlsxMetadata
  pptx?: PptxMetadata
  pdf?: PdfMetadata
  image?: ImageMetadata
}

export interface PdfMetadata {
  title?: string
  author?: string
  subject?: string
  producer?: string
  pageSize?: PdfPageSize
  pageCount: number
}

export interface PdfPageSize {
  width: number
  height: number
}

export interface PptxMetadata {
  title?: string
  author?: string
  subject?: string
  slideCount: number
}

export interface SimilarityMatch {
  referenceIndex: number
  similarityPercentage: number
}

export interface TextMetadata {
  lineCount: number
  wordCount: number
  characterCount: number
  nonWhitespaceCharacterCount: number
}

export interface XlsxMetadata {
  sheetCount: number
  sheetNames: Array<string>
  rowCount: number
  columnCount: number
  cellCount: number
}
