/* auto-generated by NAPI-RS */
/* eslint-disable */
export interface BatchItemResult {
  index: number
  outcome: ExtractionOutcome
}

export interface BatchOptions {
  extraction?: ExtractionOptions
  concurrency?: number
  maxTotalInputBytes?: number
  maxTotalOutputBytes?: number
  maxDocuments?: number
}

export interface BatchResult {
  items: Array<BatchItemResult>
  summary: BatchSummary
}

export interface BatchSummary {
  successCount: number
  partialCount: number
  errorCount: number
}

export declare const enum DecodingPolicy {
  Strict = 'strict',
  Replace = 'replace'
}

export interface Dimensions {
  width: number
  height: number
}

export declare const enum DocumentFormat {
  Text = 'text',
  Docx = 'docx',
  Xlsx = 'xlsx',
  Pptx = 'pptx',
  Pdf = 'pdf',
  Image = 'image'
}

export interface DocumentMetadata {
  properties: DocumentProperties
  statistics?: TextStatistics
  format: FormatMetadata
}

export interface DocumentProperties {
  title?: string
  author?: string
  subject?: string
  creator?: string
  producer?: string
  created?: string
  modified?: string
}

export declare const enum ErrorCode {
  UnsupportedFormat = 'UNSUPPORTED_FORMAT',
  FormatMismatch = 'FORMAT_MISMATCH',
  InvalidDocument = 'INVALID_DOCUMENT',
  DecodeFailed = 'DECODE_FAILED',
  LimitExceeded = 'LIMIT_EXCEEDED',
  OcrFailed = 'OCR_FAILED',
  InternalError = 'INTERNAL_ERROR'
}

/** Extract one document asynchronously. Document failures resolve as error outcomes. */
export declare function extract(input: ExtractionInput, options?: ExtractionOptions | undefined | null): Promise<ExtractionOutcome>

/** Extract an ordered batch with per-document failure isolation and bounded concurrency. */
export declare function extractBatch(inputs: Array<ExtractionInput>, options?: BatchOptions | undefined | null): Promise<BatchResult>

export interface ExtractionError {
  code: ErrorCode
  message: string
  stage: string
}

export interface ExtractionInput {
  data: Buffer
  id?: string
  name?: string
  mimeType?: string
}

export interface ExtractionOptions {
  selection?: ExtractionSelection
  statistics?: boolean
  text?: TextOptions
  ocr?: OcrMode
  limits?: ResourceLimits
  metrics?: boolean
}

export type ExtractionOutcome =
  | { status: 'success'; result: ExtractionResult }
  | { status: 'partial'; result: ExtractionResult }
  | { status: 'error'; source: SourceInfo; error: ExtractionError }

export interface ExtractionResult {
  source: SourceInfo
  text?: string
  encoding?: string
  metadata?: DocumentMetadata
  warnings: Array<ExtractionWarning>
  metrics?: ProcessingMetrics
}

export declare const enum ExtractionSelection {
  Text = 'text',
  Metadata = 'metadata',
  Both = 'both'
}

export interface ExtractionWarning {
  code: string
  message: string
  location?: string
}

export type FormatMetadata =
  | { kind: 'text' }
  | { kind: 'docx'; details: WordMetadata }
  | { kind: 'xlsx'; details: SpreadsheetMetadata }
  | { kind: 'pptx'; details: PresentationMetadata }
  | { kind: 'pdf'; details: PdfMetadata }
  | { kind: 'image'; details: ImageMetadata }

export interface GeoLocation {
  latitude?: number
  longitude?: number
}

export interface ImageMetadata {
  width: number
  height: number
  format?: string
  cameraMake?: string
  cameraModel?: string
  datetimeOriginal?: string
  location: GeoLocation
}

export declare const enum OcrMode {
  Disabled = 'disabled',
  Fast = 'fast',
  Balanced = 'balanced',
  Accurate = 'accurate'
}

export interface PdfMetadata {
  pageCount: number
  pageSizePoints?: Dimensions
}

export interface PresentationMetadata {
  slideCount: number
}

export interface ProcessingMetrics {
  queueTimeMs: number
  processingTimeMs: number
}

export interface ResourceLimits {
  maxInputBytes?: number
  maxOutputBytes?: number
  maxDecompressedBytes?: number
  maxArchiveEntries?: number
  maxImagePixels?: number
  maxWarnings?: number
}

export interface SheetMetadata {
  name: string
  rowCount: number
  columnCount: number
  cellCount: number
}

export interface SourceInfo {
  id?: string
  name?: string
  byteLength: number
  declaredMimeType?: string
  mimeType?: string
  format?: DocumentFormat
}

export interface SpreadsheetMetadata {
  sheets: Array<SheetMetadata>
}

export interface TextOptions {
  encoding?: string
  decoding?: DecodingPolicy
}

export interface TextStatistics {
  lineCount: number
  wordCount: number
  characterCount: number
  nonWhitespaceCharacterCount: number
}

export interface WordMetadata {
  paragraphCount: number
  tableCount: number
  imageCount: number
  hyperlinkCount: number
}
