import { defineConfig } from 'vite-plus';

export default defineConfig({
  fmt: {
    sortPackageJson: false,
    sortImports: {
      groups: [
        'type-import',
        ['side_effect'],
        ['builtin'],
        ['external'],
        ['internal'],
        ['parent'],
        ['sibling'],
        ['index'],
      ],
      newlinesBetween: false,
    },
    singleQuote: true,
    ignorePatterns: [
      '.agents',
      'CHANGELOG.md',
      '.vscode',
      'index.js',
      'index.mjs',
      'package-template.wasi-browser.js',
      'package-template.wasi.cjs',
      'wasi-worker-browser.mjs',
      'wasi-worker.mjs',
      'index.d.ts',
      '*.toml',
    ],
  },
  lint: {
    plugins: ['typescript', 'unicorn', 'import', 'oxc'],
    jsPlugins: [
      {
        name: 'vite-plus',
        specifier: 'vite-plus/oxlint-plugin',
      },
    ],
    categories: {
      correctness: 'error',
      suspicious: 'warn',
      perf: 'warn',
    },
    rules: {
      'vite-plus/prefer-vite-plus-imports': 'error',

      'no-console': [
        'warn',
        {
          allow: ['warn', 'error', 'info'],
        },
      ],
      'eslint/no-underscore-dangle': [
        'warn',
        {
          allow: ['__dirname', '__filename'],
        },
      ],
      'no-debugger': 'error',
      'no-var': 'error',
      'prefer-const': 'error',
      'eslint/no-unused-vars': [
        'error',
        {
          argsIgnorePattern: '^_',
          varsIgnorePattern: '^_',
        },
      ],

      'typescript/no-floating-promises': 'error',
      'typescript/no-misused-promises': 'error',
      'typescript/await-thenable': 'error',
      'typescript/no-unsafe-assignment': 'warn',
      'typescript/no-unsafe-argument': 'error',
      'typescript/no-unsafe-call': 'error',
      'typescript/no-unsafe-member-access': 'error',
      'typescript/no-unsafe-return': 'error',
      'typescript/no-implied-eval': 'error',
      'typescript/only-throw-error': 'error',
      'typescript/require-array-sort-compare': 'error',
      'typescript/no-deprecated': 'warn',
      'typescript/require-await': 'warn',
      'typescript/restrict-template-expressions': 'warn',
      'typescript/unbound-method': 'error',
      'typescript/switch-exhaustiveness-check': 'warn',
      'typescript/prefer-nullish-coalescing': 'warn',
      'typescript/prefer-optional-chain': 'warn',
      'typescript/no-explicit-any': 'warn',
      'typescript/no-non-null-assertion': 'warn',
      'typescript/consistent-type-imports': 'warn',
      'typescript/consistent-type-exports': 'warn',
      'typescript/no-import-type-side-effects': 'error',
      'typescript/no-duplicate-enum-values': 'error',
      'typescript/no-duplicate-type-constituents': 'error',
      'typescript/no-redundant-type-constituents': 'error',
      'typescript/no-misused-spread': 'error',
      'typescript/no-base-to-string': 'error',
      'typescript/no-array-delete': 'error',
      'typescript/no-for-in-array': 'error',
      'typescript/no-meaningless-void-operator': 'error',
      'typescript/no-confusing-non-null-assertion': 'warn',
      'typescript/no-confusing-void-expression': 'warn',
      'typescript/ban-ts-comment': 'warn',
      'typescript/consistent-generic-constructors': 'warn',
      'typescript/consistent-indexed-object-style': 'warn',
      'typescript/array-type': 'warn',
      'typescript/no-inferrable-types': 'warn',
      'typescript/no-empty-object-type': 'warn',
      'typescript/no-invalid-void-type': 'warn',
      'typescript/no-dynamic-delete': 'warn',
      'typescript/no-namespace': 'warn',
      'typescript/no-require-imports': 'warn',
      'typescript/adjacent-overload-signatures': 'warn',

      'unicorn/no-instanceof-array': 'warn',
      'unicorn/no-invalid-fetch-options': 'error',
      'unicorn/no-invalid-remove-event-listener': 'error',
      'unicorn/no-thenable': 'error',
      'unicorn/no-await-in-promise-methods': 'error',
      'unicorn/catch-error-name': 'warn',
      'unicorn/error-message': 'warn',
      'unicorn/no-new-array': 'warn',
      'unicorn/no-null': 'off',

      'import/no-duplicates': 'error',
      'import/no-cycle': 'warn',
      'import/no-self-import': 'error',
      'import/no-mutable-exports': 'warn',
      'import/newline-after-import': 'warn',

      'oxc/no-accumulating-spread': 'error',
    },
    overrides: [
      {
        files: ['benchmark/**/*.ts', '__test__/**/*.ts', 'scripts/**/*.ts'],
        rules: { 'eslint/no-await-in-loop': 'off' },
      },
    ],
    options: {
      typeAware: true,
      typeCheck: true,
    },
    ignorePatterns: ['.agents/**', 'index.js', 'index.mjs', 'index.d.ts', 'wasi-worker*.mjs'],
  },
  run: {
    cache: {
      tasks: true,
      scripts: false,
    },
  },
});
